### ISSUE TITLE
UmweltMobilCheck / EcoPassenger as API

### ISSUE THREAD

**Issue by leomelzer** [dbsystel/Bahn-API#4]
Hello,
I wanted to check whether the very handy UmweltMobilCheck is available as an API. I think the data is super useful and great for calculating e.g. Co2 emissions for different travel modes.

E.g. Augsburg -> Berlin

<img width="963" alt="Screenshot 2019-11-07 at 14 44 37" src="https://user-images.githubusercontent.com/23313/68394435-1cd56980-016e-11ea-9948-4af089e62cf7.png">

Obviously there are a lot of variables but the data can serve as a great baseline for comparisons, visualizations and so on. 

I've found the documentation https://www.bahn.de/wmedia/view/mdb/media/intern/umc_grundlagenbericht_2019.pdf as well as the service in the background (?) http://ecopassenger.hafas.de/bin/query.exe/en?L=vs_uic but no information about programmatic access.

Do you have any hints whether this is (a) available or (b) planned to be available?

Thanks!

**Comment by jschirrmacher** [comment]
Try to contact environnement2@uic.org, they should be able to tell.

**Comment by leomelzer** [comment]
@jschirrmacher Thanks, I'll give that a try and will share the response here.

**Comment by leomelzer** [comment]
I've received a very fast response:

> Unfortunately, no API has been created for EcoPassenger,
>
> We have received a lot of similar requests and will certainly consider them for the next improvement step. 

Unfortunately we'll have to wait a bit longer.

For now I'll look at https://triptocarbon.xyz/

**Comment by jschirrmacher** [comment]
Triptocarbon looks great!
Maybe we should add this API here as well...

**Comment by jschirrmacher** [comment]
Would you mind to add a PR for that, @leomelzer ?
